categories_per_page: 10
size: 80
per_page: 5
size_avartar: 50
word_filter: {learned: "learned", not_learned: "not_learned", all: "show_all"}
category:
  per_page: 10
  per_word: 10
all: "ALL"
admin:
  words:
    answer_max_size: 5
    answer_min_size: 2
    default_size_word_answers: 4
  users:
    per_page: 5
    image_size: 50
words_in_each_lesson: 10
number_word_require: 15
answertimes: 4
answer_default: 2
max_answer: 4
